### ISSUE TITLE
Issue with NextJs 13 and Mantine v7

### ISSUE THREAD

**Issue by ajdiyassin** [jotaijs/jotai-devtools#104]
I'm getting the following errors when using mantine v7

```
⨯ node_modules\@mantine\prism\cjs\Prism\Prism.styles.js (7:0) @ eval
⨯ TypeError: core.createStyles is not a function

⚠ ./node_modules/@mantine/prism/esm/PrismTabs/PrismTabs.styles.js
Attempted import error: 'createStyles' is not exported from '@mantine/core' (imported as 'createStyles').
```

After checking docs I found this 

> createStyles function is no longer available in 7.0. Use [CSS Modules](https://mantine.dev/styles/css-modules/) instead.

is support for mantine v7 planned or we should use v6?
[migration guide](https://mantine.dev/guides/6x-to-7x/)

**Comment by arjunvegda** [comment]
Hi @ajdiyassin 

I'm planning to work on migrating to V7 later this month. We're also accepting PRs if you'd like to contribute. 

For now, would you be able to use V6 instead?

**Comment by ajdiyassin** [comment]
> Hi @ajdiyassin
> 
> I'm planning to work on migrating to V7 later this month. We're also accepting PRs if you'd like to contribute.
> 
> For now, would you be able to use V6 instead?

I have migrated to v6 for now. I had to change a few things to make it run but I would love to use v7 since the syntax is cleaner

Thank you, I'm glad you are planning to support v7 of mantine.
