### ISSUE TITLE
Missing style.css

### ISSUE THREAD

**Issue by ramiel** [jotaijs/jotai-devtools#134]
The documentation [reports](https://github.com/jotaijs/jotai-devtools?tab=readme-ov-file#migrate-%C6%92rom-emotionreact-to-native-css) that the style can be imported and the dependency to @emotion/react can be removed. I installed latest version and this is not working. I also noticed the package has mantine v6 as dependency while in the repo it's already v7. Is this something syet to be released?

**Comment by arjunvegda** [comment]
Sorry, I was waiting for the docs for jotai.org to be released before releasing this version.

Please try [v0.9.0](https://github.com/jotaijs/jotai-devtools/releases/tag/v0.9.0)

**Comment by ramiel** [comment]
Oh, so quick. Thanks!
