### ISSUE TITLE
CSS leaking

### ISSUE THREAD

**Issue by marviobezerra** [jotaijs/jotai-devtools#138]
There is CSS leaking after updating from `0.8.0` to `0.9.0`. It's setting background color, font, and others on components that are not Jotai Dev tools.

I noticed that it's adding the whole `@mantine` css to my project.

**Comment by arjunvegda** [comment]
Thanks for reaching out!

We have a known issue when customers use Mantine in their main app along with Jotai, the theme would not work as expected (light/dark mode). Our recommendation is to sync the theme via props. Please see [this warning](https://github.com/jotaijs/jotai-devtools/pull/129).

If this issue is different, could you please create a small repro? Happy to look into it.

**Comment by marviobezerra** [comment]
I don't use Mantine, in my case I use Panda CSS. Moreover, importing the CSS file, based on the documentation, leaks Mantine to all my application affecting all my styles. Also, it happen if I'm running in dev or prod mode. The devtools is supposed to be available on dev more, correct?

**Comment by arjunvegda** [comment]
Could you please create a small repro perhaps on CSB?

**Comment by arjunvegda** [comment]
I think I know what's going on here. We're including global styles that affect the `body` tag. For now, could you try overriding your style with `!important` while I look into the fix?

**Comment by arjunvegda** [comment]
Hey @marviobezerra 

Could you test this canary tag and see if that fixes the issue for you? - https://ci.codesandbox.io/status/jotaijs/jotai-devtools/pr/139/builds/496213 (Follow Local Install Instructions)

**Comment by marviobezerra** [comment]
I'll try tomorrow morning and post back. Thanks for the quick response.

**Comment by sebinsua** [comment]
@arjunvegda It's still broken because of these styles:

![seems-to-still-do-global-things](https://github.com/jotaijs/jotai-devtools/assets/152098/93ea47a8-b656-4061-bfe1-4ebbd4ea4469)

Particularly `font-size: inherit` is causing the size of my buttons to be wildly off what they should be.

**Comment by arjunvegda** [comment]
@sebinsua  - you could also downgrade it to 0.8.0 temporarily until we figure this out. Sorry for the hassle!

Re: css-reset styles, what's a good way to remove them? I think the inherit problem is that Mantine is not designed to be used for libraries 🤔 But it drastically helps us in adding new features without having to maintain our own library.

Should we write our own post css plugin that removes the css reset styles?

**Comment by marviobezerra** [comment]
I tried and it still leaking. I downgraded to 0.8.0 and it's working.

**Comment by arjunvegda** [comment]
Could you folks test the latest change https://ci.codesandbox.io/status/jotaijs/jotai-devtools/pr/139/builds/496725 ?

**Comment by sebinsua** [comment]
> Could you folks test the latest change https://ci.codesandbox.io/status/jotaijs/jotai-devtools/pr/139/builds/496725 ?

This seems to be working for me.

**Comment by kvnxiao** [comment]
@arjunvegda this is still not fixed on `https://pkg.csb.dev/jotaijs/jotai-devtools/commit/992cb72f/jotai-devtools`. I am using tailwindcss and the default "light" theme is overwriting some default global CSS styling to be black.

**Comment by arjunvegda** [comment]
Thanks for reporting @kvnxiao! Could you try this tag `https://pkg.csb.dev/jotaijs/jotai-devtools/commit/57787cb3/jotai-devtools/_pkg.tgz`? If this does not fix the issue, then could you please create a small repro on CodeSandbox?

**Comment by pulsedemon** [comment]
@arjunvegda I've been having the same issue.  installed from https://pkg.csb.dev/jotaijs/jotai-devtools/commit/57787cb3/jotai-devtools/_pkg.tgz and can confirm this fixes it for me

**Comment by arjunvegda** [comment]
Released the fix in [v0.9.1](https://github.com/jotaijs/jotai-devtools/releases/tag/v0.9.1). Please feel free to re-open this issue if the problem persists.

**Comment by sebinsua** [comment]
thank you for this!

**Comment by Elvincth** [comment]
The same issue in v0.10.0 it leaks the CSS and alters mantine menu style.

**Comment by mek-earnin** [comment]
We don't use mantine but we have this issue where jotai-devtools spits out font-face with a global name "Inter" which overrides our custom font-weight for "Inter".
![Image](https://github.com/user-attachments/assets/d3ed742e-ba9d-4166-9a07-6a8351be9a06)

Our designer wants 400 500 to be regular weight so we have this font face.
![Image](https://github.com/user-attachments/assets/b6780b7b-8613-486c-834b-38429cac6315)

But the code from devtool overrides the our font-face declaration on local dev server which makes implementing and comparing with the design really hard.

It seems to also spit out tons of mantine css variables
![Image](https://github.com/user-attachments/assets/79494703-f7f6-4518-a0b7-91e266be80e4)

Note: We're using `jotai-devtools@0.10.1`.

**Comment by arjunvegda** [comment]
Thanks for reporting @mek-earnin - Are you able to create a small repro? 

In the Long term, we want to move away from Mantine to maybe shadcn. Would love some help there.
