### ISSUE TITLE
React 16 compatibility

### ISSUE THREAD

**Issue by phsantiago** [jotaijs/jotai-devtools#154]
Hello, recently in a React 16 project using jotai-devtools we started getting error due to undefined useId function.

Debugging a bit I discovered that it appeared after upgrading jotai-devtools from 0.7.1 to 0.10.

I saw that internally it doesn't use React 18 useId, so it probably a lib used here installed between 0.7.1 and 0.10.0

**Comment by arjunvegda** [comment]
Thanks for reaching out! Jotai DevTools supports React 17 and above. Please see the [prerequisites](https://github.com/jotaijs/jotai-devtools?tab=readme-ov-file#%EF%B8%8F-prerequisites).
