### ISSUE TITLE
Is there a solution that supports React16?

### ISSUE THREAD

**Issue by EliazTray** [jotaijs/jotai-devtools#163]
Refer https://github.com/jotaijs/jotai-devtools/issues/154.

I knew the prerequisites. 
Do any alternatives exist?

**Comment by arjunvegda** [comment]
Thanks for reaching out @EliazTray! Unfortunately, no, we only support react 17 and above.

**Comment by EliazTray** [comment]
> Refer #154.
> 
> I knew the prerequisites. Do any alternatives exist?

I use the jotai@2.8.4 and jotai-devtools@0.7.0 for temp solution on React 16.
