### ISSUE TITLE
run time error after updating to version 0.3.0

### ISSUE THREAD

**Issue by violabg** [jotaijs/jotai-devtools#31]
after updating to version 0.3.0 I'm getting this error

```
SyntaxError: Named export 'IconAlertCircle' not found. The requested module '@tabler/icons' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from '@tabler/icons';
```
I'm using nextjs v 13.1.6 with nx mono repo

**Comment by arjunvegda** [comment]
Thanks for reaching out! 

Could you try adding "jotai-devtools" to transpile packages in the NextJs config?

https://jotai.org/docs/tools/devtools#next-js-setup?

**Comment by violabg** [comment]
thanks, is working
