### ISSUE TITLE
ShellTriggerButton icon disappears when used with CSS reset / tailwindcss

### ISSUE THREAD

**Issue by firede** [jotaijs/jotai-devtools#34]
![CleanShot 2023-03-08 at 16 07 59@2x](https://user-images.githubusercontent.com/157338/223662716-d847af35-6089-4921-a599-4e5b4059cf6d.png)

[codesandbox](https://codesandbox.io/p/sandbox/angry-brahmagupta-978mht?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A14%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A14%7D%5D&file=%2Fpages%2F_app.tsx)

I will make a Pull Request later :)

**Comment by arjunvegda** [comment]
Fixed by #35
