### ISSUE TITLE
Unable to import jotai-devtools within an expo + react native app

### ISSUE THREAD

**Issue by arjunvegda** [jotaijs/jotai-devtools#50]
### Discussed in https://github.com/jotaijs/jotai-devtools/discussions/41

Unable to import hooks from `jotai-devtools/utils` in an expo + react native app.

This should work

```ts
import { useAtomsDevtools } from 'jotai-devtools/utils';

export const AtomsDevtools = () => {
  useAtomsDevtools('store-name-here');
  return null;
};
```

See [discussions/41#discussioncomment-5393898](https://github.com/jotaijs/jotai-devtools/discussions/41#discussioncomment-5393898)
<div type='discussions-op-text'>

<sup>Originally posted by **madsbuch** March 12, 2023</sup>
We just had to stop using `jotai-devtools` as it includes a dependency on the https://mantine.dev/ framework.

Generally, it would be nice if packages like this one were headless and do not expect a document or to be run in a browser.

Anyways, nice work and thanks for the time we got to have together!</div>

**Comment by arjunvegda** [comment]
**Root cause**: Metro — expo's bundler is unable to resolve the multi-entry node module paths using `exports` field correctly (most probably due to jotai-devtools's `./dist`?).

Ideally this should be fixed by turning on the `unstable_enablePackageExports` [option](https://facebook.github.io/metro/docs/configuration/#unstable_enablepackageexports-experimental) but I couldn't work using `config.resolver.unstable_enablePackageExports = true` so  I'd suggest filing an issue with [Metro](https://github.com/facebook/metro) and getting their recommendation as well.

Here are a few fixes I could think of.

## Fix 1 (recommended)
Expo users would resolve the path (`jotai-devtools/utils`) manually by configuring `metro.config.js`. Retains type safety for `jotai-devtools/utils`.

```js
// metro.config.js
const path = require('path');
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);
config.resolver.resolveRequest = (context, moduleName, platform) => {
    if (moduleName === 'jotai-devtools/utils') {
        return {
            filePath: path.resolve(__dirname, 'node_modules/jotai-devtools/dist/utils.cjs.js'),
            type: 'sourceFile',
        };
    }

    return context.resolveRequest(context, moduleName, platform);
}
module.exports = config
```

## Fix 2 (requires further investigation)
We add `react-native` field to `jotai-devtools`'s `package.json` file to help `metro` resolve modules correctly. 
The caveat is that it only supports a string value.

**Outstanding questions** 
- How do we export the correct types i.e. `./dist/utils.d.ts` for `react-native` property?
- How do we add support for ESM? Does Metro support it?

---

I'm not a React-native expert by any means 😅 so it'd be great if someone could help me test if the hooks under `jotai-devtools/utils` work as expected 🙏

**Comment by arjunvegda** [comment]
Closing this as we have a good workaround for now. Happy to re-open if the issue persist.

**Comment by johannbuscail** [comment]
Hello @arjunvegda, is the good workaround you're talking about, the one you answered above or something else ? I can't find anything in the doc

**Comment by arjunvegda** [comment]
hey @johannbuscail  -  I was referring to "Fix 1" and "Fix 2"mentioned in the [comment above](https://github.com/jotaijs/jotai-devtools/issues/50#issuecomment-1480486726)
