### ISSUE TITLE
Build breaking in NextJS 13.2

### ISSUE THREAD

**Issue by pablocubico** [jotaijs/jotai-devtools#83]
Hi there, I'm using NextJS 13.2 and it seems that the build breaks.

At first install, I got this error (expected):
![image](https://github.com/jotaijs/jotai-devtools/assets/340766/82c16653-af59-441f-aaa5-c1757f453ab3)

Which is expected, it means I haven't added:
```
transpilePackages: ['jotai-devtools'],
```

After adding it, the build failed repeatedly saying that it couldn't find the corresponding chunk (sorry, didn't get a screenshot of that!).

I updated `react-resizable-panels` to the latest version in my project and started next again: it started working.

However, now I'm trying to reproduce the error back and I can't get it to fail again... 🤔 

So, I'm not sure what happened, I created a PR to update `react-resizable-panels` just in case, since I think updating the package won't hurt. 

Also, I'm a bit confused about the NPM Caret Version docs: https://github.com/npm/node-semver#caret-ranges-123-025-004
(check the "leftmost zero" rules...)

But the version of `react-resizable-panels` that I got when I installed `jotai-devtools` was not the latest, it was the one in `jotai-devtools`'s `package.json`. 

Related PR: https://github.com/jotaijs/jotai-devtools/pull/84

**Comment by arjunvegda** [comment]
Thanks for reaching out and for the PR!

I ran into a similar issue with both CRA and NextJS when testing this package before releasing the `0.6.0`. This is a caching issue in NextJS/Webpack. Removing the `node_modules` and `.next` directories fixed it for me. 

I'm _also_ unable to reproduce this 😟 

> But the version of react-resizable-panels that I got when I installed jotai-devtools was not the latest, it was the one in jotai-devtools's package.json.

Does caret update apply to nested dependencies? 🤔 I always thought it applied to the root (I could be wrong though)

**Comment by pablocubico** [comment]
Hmm, looks like it's a sneaky one then. I guess the dependencies could be updated anyway.

The caret rules are a bit contrived! I need to reread that...  😅
