### ISSUE TITLE
If I use npm v7.x or later, do I need to install emotion?

### ISSUE THREAD

**Issue by maroKanatani** [jotaijs/jotai-devtools#99]
Hello, thanks for this useful software !

The README.md says I need to install emotion, but if I am using npm v7.x or later, peerDependencies is also installed with it, so there seems to be no need to install it explicitly.

**Comment by arjunvegda** [comment]
Hi @maroKanatani 

Glad to hear that the tool is helpful! That's fine then! As long as the peer dependencies are installed, `<DevTools />` should work as expected.
